language: python

matrix:
  fast_finish: true

  include:
    - python: '3.5'
      env: PIP_FLAGS="--quiet --pre"
    - python: '3.6'
      env: PIP_FLAGS="--quiet --pre"
    - python: '3.7'
      dist: xenial
      sudo: required
      env: PIP_FLAGS="--quiet --pre"

    - python: '3.5'
      env: PIP_FLAGS="--quiet"
    - python: '3.6'
      env: PIP_FLAGS="--quiet"
    - python: '3.7'
      dist: xenial
      sudo: required
      env: PIP_FLAGS="--quiet"

before_install:
  - python -m pip install -q --upgrade pip
  - python -m pip install lalsuite  # to get LAL
  - python -m pip install ${PIP_FLAGS} -r requirements.txt

install:
  # note: need --editable for coverage with `which ...` to work
  - python -m pip install --editable .

script:
  - python -m pip install ${PIP_FLAGS} \
        "pytest>=3.0.0" \
        "mock ; python_version < '3'" \
        "coverage"
  - python -m coverage run -m pytest hveto/
  - python -m coverage run --append `which hveto` --help
  - python -m coverage run --append `which hveto-cache-events` --help
  - python -m coverage run --append `which hveto-trace` --help

after_success:
  - python -m pip install ${PIP_FLAGS} codecov
  - python -m codecov --flags $(uname) python${TRAVIS_PYTHON_VERSION/./}

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
